"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Lists", [
      {
        name: "Test List",
        complete: false,
        boardId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "First Location",
        complete: false,
        boardId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Second Location",
        complete: false,
        boardId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Third Location",
        complete: false,
        boardId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Hip-Hop",
        complete: false,
        boardId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Alternative Rock",
        complete: false,
        boardId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jazz",
        complete: false,
        boardId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Classics",
        complete: false,
        boardId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "First Location",
        complete: false,
        boardId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Second Location",
        complete: false,
        boardId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Third Location",
        complete: false,
        boardId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Speed-Type",
        complete: false,
        boardId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Heavy-Type",
        complete: false,
        boardId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Brawler-Type",
        complete: false,
        boardId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ranged-Type",
        complete: false,
        boardId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mystery",
        complete: false,
        boardId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nonfiction",
        complete: false,
        boardId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sci-fi",
        complete: false,
        boardId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Fantasy",
        complete: false,
        boardId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Books",
        complete: false,
        boardId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Movies",
        complete: false,
        boardId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Comedies",
        complete: false,
        boardId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dramas",
        complete: false,
        boardId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Horror",
        complete: false,
        boardId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Documentary",
        complete: false,
        boardId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Cartoons",
        complete: false,
        boardId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Lists", null, {});
  },
};
